import {test} from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
const source=readFileSync(new URL('../pages/customer/login.vue',import.meta.url),'utf8').match(/<script>([\s\S]*?)<\/script>/)[1].replace(/^import .*$/gm,'').replace('export default','return')
function fixture(){const calls=[],routes=[];const c=new Function('auth','loginWechatWithPhone','completeCustomerWechat','uni',source)({},async(p,n)=>{calls.push([p,n]);return{account:{memberId:1}}},()=>true,{showToast(){},reLaunch:o=>routes.push(o.url)});return{state:Object.assign(c.data(),c.methods),calls,routes}}
test('phone is mandatory and duplicate taps login only once',async()=>{const f=fixture();f.state.phoneRequired=true;await f.state.submit();assert.equal(f.calls.length,0);f.state.phone=13800000003;f.state.name='顾客';await Promise.all([f.state.submit(),f.state.submit()]);assert.deepEqual(f.calls,[['13800000003','顾客']]);assert.deepEqual(f.routes,['/pages/customer/home'])})
test('wechat manual login exchanges fresh code with typed phone, never a password',async()=>{const source=readFileSync(new URL('../common/wechat.js',import.meta.url),'utf8');const body=source.slice(source.indexOf('export async function loginWechatWithPhone')).split('export function parseMemberScene')[0].replace('export async function','return async function');const requests=[];let count=0;const login=new Function('request','wx','uni',body)(async o=>{requests.push(o);return{}},{login(){}},{login:o=>o.success({code:'fresh'+(++count)})});await assert.rejects(login('123'),/11位/);await login('13800000003','称呼');await login('13800000003','称呼');assert.equal(requests[0].data.code,'fresh1');assert.equal(requests[1].data.code,'fresh2');assert.equal(requests[0].data.phone,'13800000003');assert.equal(requests[0].data.password,undefined);assert.equal(requests[0].url,'/api/wechat/customer/manual-login')})

test('returning member uses WeChat without typing a phone',async()=>{const f=fixture();await f.state.submit();assert.deepEqual(f.calls,[['','']]);assert.deepEqual(f.routes,['/pages/customer/home'])})
test('new WeChat asks for phone before registration and prevents empty submission',async()=>{let calls=0;const c=new Function('auth','loginWechatWithPhone','completeCustomerWechat','uni',source)({},async()=>{calls++;return{manualPhoneRequired:true}},()=>{throw Error('must not complete')},{showToast(){}});const state=Object.assign(c.data(),c.methods);await state.submit();assert.equal(state.phoneRequired,true);assert.equal(state.loading,false);await state.submit();assert.equal(calls,1)})
