import {test} from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
const source=readFileSync(new URL('../pages/staff/records.vue',import.meta.url),'utf8').match(/<script>([\s\S]*?)<\/script>/)[1].replace(/^import .*$/gm,'').replace('export default','return')
function fixture(fetch){const calls=[];const component=new Function('api','auth','uni',source)({staffTransactions:async p=>{calls.push(p);return fetch(p)}},{can:()=>false,isLogin:()=>true},{});return{component,state:Object.assign(component.data(),component.methods),calls}}
test('records default to own staff and pass filters with pagination',async()=>{const f=fixture(async p=>({records:[{id:p.pageNum}],total:2}));f.state.keyword=' 13800000003 ';f.state.type='CONSUME';await f.state.reload();await f.state.loadMore();assert.deepEqual(f.state.rows,[{id:1},{id:2}]);assert.equal(f.calls[0].scope,'mine');assert.equal(f.calls[0].keyword,'13800000003');assert.equal(f.calls[1].pageNum,2);assert.equal(f.calls[1].type,'CONSUME')})
test('changed filters discard an older pending response',async()=>{let release;const f=fixture(p=>p.type===''?new Promise(r=>release=r):Promise.resolve({records:[{id:2}],total:1}));const first=f.state.reload();f.state.type='RECHARGE';await f.state.reload();release({records:[{id:1}],total:1});await first;assert.deepEqual(f.state.rows,[{id:2}])})
test('no store scope without permission and reversed dates do not request',async()=>{const f=fixture(async()=>({records:[],total:0}));f.state.setScope('store');assert.equal(f.state.scope,'mine');assert.equal(f.calls.length,0);f.state.startDate='2026-09-09';f.state.endDate='2026-09-08';await f.state.reload();assert.equal(f.calls.length,0);assert(f.state.error.includes('开始日期'))})
test('records refresh clears stale data on failure',async()=>{const f=fixture(async()=>{throw{message:'无权限'}});f.state.rows=[{id:1}];await f.state.reload();assert.equal(f.state.rows.length,0);assert.equal(f.state.error,'无权限')})
